var parse_constants = {
	'REQUEST_HELP': 0,
	'MATCH_REPORT_WIN': 1,
	'MATCH_REPORT_LOSE': 2,
	'MATCH_REPORT_AMBIGUOUS': 3,
	'JOIN_TOURNEY': 4,
	'CREATE_TOURNEY': 5,
	'START_TOURNEY': 6,
	'END_TOURNEY': 7,
	'DROP_TOURNEY': 8,
	'REPORT': 9,
	'VOTE_GUILTY': 10,
	'VOTE_INNOCENT': 11,
	'CHANGE_SETTINGS': 12,
	'YES': 13,
	'NO': 14,
	'UNIDENTIFIED': 15

};
//
module.exports = parse_constants;